#!/usr/bin/env tsx
/**
 * Converts scraped JPGs to WebP in 3 sizes + generates blur placeholders.
 *
 * Input:  scripts/scraper/output/instagram/<postId>/<n>.jpg
 * Output: public/images/projects/<postId>/<n>-sm.webp   (480px)
 *         public/images/projects/<postId>/<n>-md.webp   (960px)
 *         public/images/projects/<postId>/<n>-lg.webp   (1920px)
 *         src/data/blur-placeholders.ts
 */

import sharp from 'sharp'
import * as fs from 'fs'
import * as path from 'path'

const INPUT_DIR = path.join(process.cwd(), 'scripts/scraper/output/instagram')
const OUTPUT_DIR = path.join(process.cwd(), 'public/images/projects')
const BLUR_OUTPUT = path.join(process.cwd(), 'src/data/blur-placeholders.ts')

const SIZES = [
  { suffix: 'sm', width: 480 },
  { suffix: 'md', width: 960 },
  { suffix: 'lg', width: 1920 },
] as const

async function toBlurDataUrl(inputPath: string): Promise<string> {
  const buf = await sharp(inputPath).resize(10, 10, { fit: 'inside' }).webp({ quality: 20 }).toBuffer()
  return `data:image/webp;base64,${buf.toString('base64')}`
}

async function processImage(inputPath: string, postId: string, idx: number): Promise<{ key: string; blur: string } | null> {
  if (!fs.existsSync(inputPath)) return null

  const outDir = path.join(OUTPUT_DIR, postId)
  fs.mkdirSync(outDir, { recursive: true })

  const { width: origW = 1920 } = await sharp(inputPath).metadata()

  for (const { suffix, width } of SIZES) {
    if (width > origW) continue
    await sharp(inputPath)
      .resize(width, null, { fit: 'inside', withoutEnlargement: true })
      .webp({ quality: 85, effort: 4 })
      .toFile(path.join(outDir, `${idx}-${suffix}.webp`))
  }

  const lgPath = path.join(outDir, `${idx}-lg.webp`)
  if (!fs.existsSync(lgPath)) {
    await sharp(inputPath).webp({ quality: 90 }).toFile(lgPath)
  }

  console.log(`  ${postId}/${idx} -> WebP`)
  return { key: `${postId}/${idx}`, blur: await toBlurDataUrl(inputPath) }
}

async function main() {
  if (!fs.existsSync(INPUT_DIR)) {
    console.error('No input — run scrape:instagram first')
    process.exit(1)
  }
  fs.mkdirSync(OUTPUT_DIR, { recursive: true })

  const postIds = fs.readdirSync(INPUT_DIR).filter((n) => fs.statSync(path.join(INPUT_DIR, n)).isDirectory())
  const blurMap: Record<string, string> = {}

  for (const postId of postIds) {
    const files = fs.readdirSync(path.join(INPUT_DIR, postId)).filter((f) => /\.(jpg|jpeg|png|webp)$/i.test(f))
    console.log(`\n${postId} (${files.length} images)`)
    for (const file of files) {
      const idx = parseInt(path.basename(file, path.extname(file)), 10)
      const result = await processImage(path.join(INPUT_DIR, postId, file), postId, isNaN(idx) ? 0 : idx)
      if (result) blurMap[result.key] = result.blur
    }
  }

  const ts = [
    '// Auto-generated by scripts/scraper/optimize-images.ts',
    '',
    `export const blurPlaceholders: Record<string, string> = ${JSON.stringify(blurMap, null, 2)}`,
    '',
    'export function getBlurPlaceholder(postId: string, index: number): string | undefined {',
    '  return blurPlaceholders[`${postId}/${index}`]',
    '}',
    '',
  ].join('\n')

  fs.writeFileSync(BLUR_OUTPUT, ts)
  console.log(`\nDone — ${Object.keys(blurMap).length} images optimized`)
  console.log(`Blur map written to ${BLUR_OUTPUT}`)
}

main().catch((err) => { console.error(err); process.exit(1) })
