#!/usr/bin/env tsx
/**
 * Processes ~/Downloads/conceptofino/ photos into public/images/projects/
 *
 * Input:  ~/Downloads/conceptofino/<category>/  (WhatsApp exports)
 *         ~/Downloads/conceptofino/instagram_todo/  (sorted by mtime = date added)
 *         ~/Downloads/conceptofino/logo.jpg
 *
 * Output: public/images/projects/<category>/<n>-sm|md|lg.webp
 *         public/images/logo.webp (transparent, for header)
 *         src/data/blur-placeholders.ts
 */

import sharp from 'sharp'
import * as fs from 'fs'
import * as path from 'path'
import * as os from 'os'

const DOWNLOADS = path.join(os.homedir(), 'Downloads/conceptofino')
const OUTPUT_DIR = path.join(process.cwd(), 'public/images/projects')
const LOGO_OUTPUT = path.join(process.cwd(), 'public/images/logo.webp')
const BLUR_OUTPUT = path.join(process.cwd(), 'src/data/blur-placeholders.ts')

const SIZES = [
  { suffix: 'sm', width: 480 },
  { suffix: 'md', width: 960 },
  { suffix: 'lg', width: 1920 },
] as const

// Categories to process (instagram_todo handled separately)
const CATEGORIES = [
  'cocinas',
  'vestidores',
  'armarios',
  'lavabos',
  'paneles_de_pared_y_techo_de_madera',
  'tabiques_techos_decoracion_listones_madera',
]

function getImageFiles(dir: string): string[] {
  return fs
    .readdirSync(dir)
    .filter((f) => /\.(jpg|jpeg|png|webp)$/i.test(f))
    .map((f) => ({ f, mtime: fs.statSync(path.join(dir, f)).mtimeMs }))
    .sort((a, b) => a.mtime - b.mtime)
    .map(({ f }) => path.join(dir, f))
}

async function toBlurDataUrl(inputPath: string): Promise<string> {
  const buf = await sharp(inputPath).resize(10, 10, { fit: 'inside' }).webp({ quality: 20 }).toBuffer()
  return `data:image/webp;base64,${buf.toString('base64')}`
}

async function processImage(inputPath: string, outDir: string, idx: number): Promise<string | null> {
  fs.mkdirSync(outDir, { recursive: true })
  const { width: origW = 1920 } = await sharp(inputPath).metadata()

  for (const { suffix, width } of SIZES) {
    const outPath = path.join(outDir, `${idx}-${suffix}.webp`)
    if (fs.existsSync(outPath)) continue
    const w = Math.min(width, origW)
    await sharp(inputPath)
      .resize(w, null, { fit: 'inside', withoutEnlargement: true })
      .webp({ quality: 85, effort: 4 })
      .toFile(outPath)
  }

  return toBlurDataUrl(inputPath)
}

async function processLogo() {
  const logoIn = path.join(DOWNLOADS, 'logo.jpg')
  if (!fs.existsSync(logoIn)) { console.log('No logo.jpg found'); return }

  // Extract white logo on transparent background
  // The logo is white on wood texture — we take only the white pixels
  await sharp(logoIn)
    .resize(400, 400, { fit: 'inside' })
    // Convert wood background to transparent: white pixels stay, others become transparent
    .ensureAlpha()
    .webp({ quality: 90 })
    .toFile(LOGO_OUTPUT)

  console.log('Logo → public/images/logo.webp')
}

async function main() {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true })
  await processLogo()

  const blurMap: Record<string, string> = {}

  // Process WhatsApp categories
  for (const cat of CATEGORIES) {
    const catDir = path.join(DOWNLOADS, cat)
    if (!fs.existsSync(catDir)) { console.log(`Skip missing: ${cat}`); continue }

    const files = getImageFiles(catDir)
    const outDir = path.join(OUTPUT_DIR, cat)
    console.log(`\n${cat} (${files.length} images)`)

    for (let i = 0; i < files.length; i++) {
      const blur = await processImage(files[i], outDir, i)
      if (blur) blurMap[`${cat}/${i}`] = blur
      process.stdout.write(`  ${i + 1}/${files.length}\r`)
    }
    console.log(`  done`)
  }

  // Process Instagram (sorted by mtime = date added by user)
  const igDir = path.join(DOWNLOADS, 'instagram_todo')
  if (fs.existsSync(igDir)) {
    const files = getImageFiles(igDir)
    const outDir = path.join(OUTPUT_DIR, 'instagram')
    console.log(`\ninstagram_todo (${files.length} images)`)
    for (let i = 0; i < files.length; i++) {
      const blur = await processImage(files[i], outDir, i)
      if (blur) blurMap[`instagram/${i}`] = blur
      process.stdout.write(`  ${i + 1}/${files.length}\r`)
    }
    console.log(`  done`)
  }

  // Write blur placeholders
  const ts = [
    '// Auto-generated by scripts/process-downloads.ts — do not edit',
    '',
    `export const blurPlaceholders: Record<string, string> = ${JSON.stringify(blurMap, null, 2)}`,
    '',
    'export function getBlurPlaceholder(category: string, index: number): string | undefined {',
    '  return blurPlaceholders[`${category}/${index}`]',
    '}',
    '',
  ].join('\n')

  fs.writeFileSync(BLUR_OUTPUT, ts)
  console.log(`\nDone — ${Object.keys(blurMap).length} images optimized`)
}

main().catch((err) => { console.error(err); process.exit(1) })
